# api:
#     resource: "@ApiBundle/Controller/"
#     type:     annotation
#     prefix:   /

api:
    type: rest
    prefix: /
    resource: "@ApiBundle/Resources/config/routes.yml"

## For API
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc



core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
